In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
b = a

In [4]:
print(b is a)

True


In [5]:
b.shape = 3,4

In [6]:
print(a.shape)

(3, 4)


In [7]:
print(id(a))

1924436721376


In [8]:
print(id(b))

1924436721376


In [10]:
c = a.view()

In [11]:
print(c is a)

False


In [12]:
c.shape = 2,6

In [13]:
print(a.shape)

(3, 4)


In [14]:
c[0,4]=124

In [15]:
print(a)#公用一套值

[[  0   1   2   3]
 [124   5   6   7]
 [  8   9  10  11]]


In [16]:
print(id(a))

1924436721376


In [17]:
print(id(c))

1924436769648


In [18]:
d = a.copy()#深拷贝

In [19]:
d is a

False

In [20]:
d[0,0] = 999

In [21]:
print(d)

[[999   1   2   3]
 [124   5   6   7]
 [  8   9  10  11]]


In [22]:
print(a)

[[  0   1   2   3]
 [124   5   6   7]
 [  8   9  10  11]]
