In [22]:
import numpy as np

In [23]:
a = np.floor(10*np.random.random((2,2)))

In [24]:
b = np.floor(10*np.random.random((2,2)))

In [25]:
print(a)

[[3. 0.]
 [1. 6.]]


In [26]:
print(b)

[[8. 7.]
 [0. 4.]]


In [27]:
print(np.hstack((a,b)))#拼接 横向

[[3. 0. 8. 7.]
 [1. 6. 0. 4.]]


In [28]:
print(np.vstack((a,b)))#拼接 列拼接

[[3. 0.]
 [1. 6.]
 [8. 7.]
 [0. 4.]]


In [29]:
a  = np.floor(10*np.random.random((2,12)))

In [30]:
print(a)

[[2. 1. 4. 6. 1. 4. 3. 9. 1. 0. 1. 0.]
 [3. 8. 6. 0. 9. 0. 9. 3. 2. 9. 1. 3.]]


In [31]:
print(np.hsplit(a,3))#切割为4份

[array([[2., 1., 4., 6.],
       [3., 8., 6., 0.]]), array([[1., 4., 3., 9.],
       [9., 0., 9., 3.]]), array([[1., 0., 1., 0.],
       [2., 9., 1., 3.]])]


In [32]:
print(np.hsplit(a,(3,4)))# 在第三列  和 第四列 进行切分

[array([[2., 1., 4.],
       [3., 8., 6.]]), array([[6.],
       [0.]]), array([[1., 4., 3., 9., 1., 0., 1., 0.],
       [9., 0., 9., 3., 2., 9., 1., 3.]])]


In [36]:
print(a)

[[2. 1. 4. 6. 1. 4. 3. 9. 1. 0. 1. 0.]
 [3. 8. 6. 0. 9. 0. 9. 3. 2. 9. 1. 3.]]


In [37]:
np.vsplit(a,2)

[array([[2., 1., 4., 6., 1., 4., 3., 9., 1., 0., 1., 0.]]),
 array([[3., 8., 6., 0., 9., 0., 9., 3., 2., 9., 1., 3.]])]