In [1]:
import numpy as np

In [2]:
data = np.sin(np.arange(20)).reshape(5,4)

In [3]:
print(data)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]


In [4]:
ind = data.argmax(axis=0)#找到最大索引

In [5]:
print(ind)

[2 0 3 1]


In [6]:
data_max = data[ind,range(data.shape[1])]

In [7]:
print(data_max)#打印找到的最大值

[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [8]:
a = np.arange(0,40,10)

In [9]:
print(a)

[ 0 10 20 30]


In [12]:
b = np.tile(a,(3,4))#行列进行扩展

In [13]:
print(b)

[[ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30  0 10 20 30]]


In [14]:
a = np.array([[4,3,5],[1,2,1]])

In [15]:
print(a)

[[4 3 5]
 [1 2 1]]


In [16]:
b = np.sort(a,axis=1)#排序 行

In [17]:
print(b)

[[3 4 5]
 [1 1 2]]


In [18]:
a = np.array([4,3,1,2])

In [19]:
j = np.argsort(a)#求最大值索引

In [20]:
print(j)

[2 3 1 0]


In [21]:
print(a[j])# 排序完结果

[1 2 3 4]
