In [37]:
import tensorflow as tf 

矩阵乘法
矩阵乘法是最常见的方法，也是在深度神经网络中用的很多的加权求和中的加权操作。

两个矩阵做乘法，必须满足第一个矩阵的第二维和第二个矩阵的第一维要相等，结果的维度等于第一个矩阵的第一维和第二个矩阵的第二维。 比如mn的矩阵和np的矩阵，结果为m*p维矩阵。计算过程是第一个矩阵的每一行和第二个矩阵的每一列，即两个向量相乘。

输出结果是5*10的矩阵

In [31]:
# 定义输入数据为维度5*3的矩阵
input_data = tf.zeros(shape=[5,3],name="input_data")

In [32]:
# 定义权重为维度3*10的矩阵
weight=tf.Variable(tf.ones(shape=[3,10],name="weight"))

In [35]:
result = tf.matmul(input_data,weight,name="result")

In [36]:
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print("result:\n",session.run(result))

result:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


点乘
点乘计算要求两个矩阵拥有相同的维度，相同下标的元素一一对应相乘，在神经风格中，风格损失格拉姆矩阵的计算时就使用了点乘。

比如mn维矩阵只能和mn维矩阵相乘，获得的结果还是m*n维矩阵。

输出结果是一个5*3的矩阵


In [39]:
# 定义输入数据为维度5*3的矩阵
input_data = tf.zeros(shape=[5,3],name="input_data")
# 定义权重为维度5*3的矩阵
weight = tf.Variable(tf.ones(shape=[5,3]),name="weight")
# 计算矩阵乘法结果
result = tf.multiply(input_data,weight,name="result")
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print("result : \n" ,session.run(result))

result : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a = tf.zeros(shape=[1,2])

In [16]:
print(a)

Tensor("zeros_7:0", shape=(1, 2), dtype=float32)


In [17]:
sess = tf.InteractiveSession()

In [18]:
print(sess.run(a))

[[0. 0.]]


In [19]:
W = tf.Variable(tf.zeros(shape=[1,2]))

In [20]:
tensor = tf.zeros(shape=[1,2])
variable = tf.Variable(tensor)
sess = tf.InteractiveSession()
# print(sess.run(variable))  # 会报错
sess.run(tf.initialize_all_variables()) # 对variable进行初始化
print(sess.run(variable))

[[0. 0.]]


In [24]:
x = tf.placeholder(tf.float32,[1, 5],name='input')
#又叫占位符，同样是一个抽象的概念。用于表示输入输出数据的格式。

In [25]:
y = tf.placeholder(tf.float32,[None, 5],name='input')